// Code generated by hertz generator.

package main

import (
	"compliance/workflow/biz/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func init() {
	dal.Init()
}

func main() {
	h := server.Default()

	register(h)
	h.Spin()
}
